import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'es' | 'fr' | 'te';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data structure
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.predict': 'Predict',
    'nav.analytics': 'Analytics',
    'nav.heatmap': 'Heatmap',
    'nav.dashboard': 'Dashboard',
    'nav.favorites': 'Favorites',
    'nav.chatbot': 'AI Assistant',
    'nav.profile': 'Profile',
    'nav.signIn': 'Sign In',
    'nav.signUp': 'Sign Up',
    'nav.signOut': 'Sign Out',
    
    // Landing Page
    'landing.title': 'Value Home Vision',
    'landing.subtitle': 'AI-Powered Real Estate Price Prediction',
    'landing.description': 'Get accurate property valuations using advanced machine learning with 95.97% precision',
    'landing.features.title': 'Why Choose Our Platform?',
    'landing.features.accuracy': 'ML Accuracy',
    'landing.features.properties': 'Properties Analyzed',
    'landing.features.predictions': 'Predictions Made',
    'landing.features.satisfaction': 'User Satisfaction',
    'landing.getStarted': 'Get Started',
    'landing.learnMore': 'Learn More',
    
    // Prediction Page
    'predict.title': 'Property Price Prediction',
    'predict.subtitle': 'Get instant property valuation using our advanced AI model',
    'predict.form.title': 'Property Details',
    'predict.form.livingArea': 'Living Area (sq ft)',
    'predict.form.lotArea': 'Lot Area (sq ft)',
    'predict.form.bedrooms': 'Number of Bedrooms',
    'predict.form.bathrooms': 'Number of Bathrooms',
    'predict.form.grade': 'House Grade (1-13)',
    'predict.form.condition': 'House Condition (1-5)',
    'predict.form.builtYear': 'Built Year',
    'predict.form.location': 'Select Location',
    'predict.form.predict': 'Predict Price',
    'predict.form.predicting': 'Predicting...',
    'predict.results.title': 'Predicted Value',
    'predict.results.confidence': 'Confidence',
    'predict.results.modelAccuracy': 'Model Accuracy',
    'predict.results.analysis': 'Market Analysis',
    'predict.form.areaExcludingBasement': 'Area Excluding Basement (sq ft)',
    'predict.form.areaOfBasement': 'Basement Area (sq ft)',
    'predict.form.postalCode': 'Postal Code',
    'predict.form.latitude': 'Latitude',
    'predict.form.longitude': 'Longitude',
    'predict.form.views': 'Number of Views',
    'predict.form.waterfront': 'Waterfront Property',
    'predict.form.renovationYear': 'Renovation Year',
    'predict.form.schoolsNearby': 'Schools Nearby',
    'predict.form.distanceFromAirport': 'Distance from Airport (km)',
    'predict.form.dimensions': 'Property Dimensions',
    'predict.form.rooms': 'Room Configuration',
    'predict.form.quality': 'Quality & Condition',
    'predict.form.history': 'Property History',
    'predict.form.locationDetails': 'Location Details',
    'predict.form.features': 'Special Features',
    'predict.form.neighborhood': 'Neighborhood & Accessibility',
    'predict.form.quickStart': 'Quick Start Presets',
    'predict.form.budgetHome': 'Budget Home',
    'predict.form.averageHome': 'Average Home',
    'predict.form.luxuryEstate': 'Luxury Estate',
    'predict.form.aiValuation': 'AI Property Valuation',
    'predict.form.poweredBy': 'Powered by 25-feature XGBoost ML model',
    'predict.form.accuracy': 'Accuracy',
    'predict.form.featuresCount': 'Features',
    'predict.form.properties': 'Properties',
    'predict.form.submitPoweredBy': 'Powered by XGBoost ML with 95.97% accuracy • Results in seconds',
    'predict.form.generateValuation': 'Generate AI Property Valuation',
    'predict.results.estimatedValue': 'Estimated Property Value',
    'predict.results.marketAnalysis': 'Market Analysis',
    'predict.results.keyInsights': 'Key Insights',
    'predict.results.investmentCalculator': 'Investment Calculator',
    'predict.results.propertyLocation': 'Property Location',
    'predict.results.downPayment': 'Down Payment',
    'predict.results.monthlyMortgage': 'Monthly Mortgage (Est.)',
    'predict.results.coordinates': 'Coordinates',
    'predict.results.priceRange': 'Price Range',
    'predict.results.locationRating': 'Location Rating',
    'predict.results.propertyGrade': 'Property Grade',
    'predict.results.investmentAdvice': 'Investment Advice',
    'predict.results.sizeFactor': 'Size Factor',
    'predict.results.locationPremium': 'Location Premium',
    'predict.results.predictionAccuracy': 'Prediction Accuracy',
    'predict.results.keyValueDrivers': 'Key Value Drivers',
    'predict.results.aiInsights': 'Get AI Insights & Compare Properties',
    'predict.results.aiInsightsDesc': 'Ask our AI assistant questions about this prediction, compare with similar properties, or get investment advice based on your specific needs.',
    'predict.results.chatAboutProperty': 'Chat About This Property',
    'predict.results.relatedProperties': 'Related Properties & Map Location',
    'predict.results.similarProperties': 'Similar Properties Found',
    'predict.results.mapLocation': 'Map Location',
    'predict.results.viewDetails': 'View Details',
    
    // Analytics Page
    'analytics.title': 'Market Analytics',
    'analytics.subtitle': 'Comprehensive real estate market insights and trends',
    'analytics.overview': 'Market Overview',
    'analytics.trends': 'Price Trends',
    'analytics.distribution': 'Price Distribution',
    'analytics.investment': 'Investment Calculator',
    'analytics.roi': 'ROI Analysis',
    'analytics.rental': 'Rental',
    'analytics.emi': 'EMI',
    'analytics.compare': 'Compare',
    'analytics.investmentDashboard': 'Investment Analytics Dashboard',
    'analytics.dashboardSubtitle': 'Make data-driven real estate decisions with ROI, rental, and EMI insights.',
    'analytics.currentlyAnalyzing': 'Currently Analyzing',
    'analytics.clearSelection': 'Clear Selection',
    'analytics.roiProjection': '10Y ROI',
    'analytics.rentalYield': 'Rental Yield',
    'analytics.monthlyEmi': 'Monthly EMI',
    'analytics.totalInterest': 'Total Interest',
    'analytics.projectionBased': 'Projection based on appreciation',
    'analytics.annualRentVs': 'Annual rent vs. property value',
    'analytics.basedOnRate': 'Based on rate and tenure',
    'analytics.overFullTenure': 'Over full loan tenure',
    'analytics.roiCalculator': 'ROI Calculator',
    'analytics.rentalAnalyzer': 'Rental Income Analyzer',
    'analytics.emiCalculator': 'EMI Calculator',
    'analytics.comparison': 'Compare',
    'analytics.purchasePrice': 'Purchase Price (CAD)',
    'analytics.loanAmount': 'Loan Amount (CAD)',
    'analytics.interestRate': 'Interest Rate (%)',
    'analytics.loanTenure': 'Loan Tenure (Years)',
    'analytics.monthlyRent': 'Expected Monthly Rent (CAD)',
    'analytics.appreciation': 'Annual Appreciation (%)',
    'analytics.investmentSummary': 'Investment Summary',
    'analytics.projectedValue': 'Projected Value (10Y)',
    'analytics.totalGains': 'Total Capital Gains',
    'analytics.returnOnInvestment': 'Return on Investment',
    'analytics.cashFlow': 'Monthly Cash Flow',
    'analytics.breakEven': 'Break-even Period',
    'analytics.rentalSummary': 'Rental Income Analysis',
    'analytics.grossYield': 'Gross Rental Yield',
    'analytics.monthlyIncome': 'Monthly Rental Income',
    'analytics.annualIncome': 'Annual Rental Income',
    'analytics.tenYearIncome': '10-Year Rental Income',
    'analytics.emiBreakdown': 'EMI Breakdown',
    'analytics.principalVsInterest': 'Principal vs Interest',
    'analytics.paymentSchedule': 'Payment Schedule Over Time',
    
    // Additional Analytics Keys
    'analytics.propertyNumber': 'Property',
    'analytics.sqft': 'sq ft',
    'analytics.grade': 'Grade',
    'analytics.configureInvestmentParameters': 'Configure investment parameters',
    'analytics.investmentCalculator': 'Investment Calculator',
    'analytics.basedOnRateAndTenure': 'Based on rate and tenure',
    'analytics.overFullLoanTenure': 'Over full loan tenure',
    
    // Predict Related Properties
    'predict.related.title': 'Related Properties',
    'predict.related.mapLocation': 'Map Location',
    'predict.related.similarProperties': 'Similar Properties Found',
    'predict.related.match': 'match',
    'predict.related.beds': 'beds',
    'predict.related.baths': 'baths',
    'predict.related.sqft': 'sqft',
    'predict.related.grade': 'Grade',
    'predict.related.waterfront': 'Waterfront',
    'predict.related.viewOnMap': 'View on map',
    'predict.related.viewDetails': 'View Details',
    'predict.related.propertyDetails': 'Property Details',
    'predict.related.gradeLuxury': 'Luxury',
    'predict.related.gradeExcellent': 'Excellent',
    'predict.related.gradeVeryGood': 'Very Good',
    'predict.related.gradeGood': 'Good',
    'predict.related.gradeAverage': 'Average',
    'predict.related.gradeBelowAverage': 'Below Average',
    'predict.related.conditionExcellent': 'Excellent',
    'predict.related.conditionVeryGood': 'Very Good',
    'predict.related.conditionGood': 'Good',
    'predict.related.conditionFair': 'Fair',
    'predict.related.conditionPoor': 'Poor',
    'predict.related.bedrooms': 'Bedrooms',
    'predict.related.bathrooms': 'Bathrooms',
    'predict.related.livingArea': 'Living Area (sq ft)',
    'predict.related.lotSize': 'Lot Size (sq ft)',
    'predict.related.buildingInfo': 'Building Information',
    'predict.related.builtYear': 'Built Year',
    'predict.related.yearsOld': 'years old',
    'predict.related.renovated': 'Renovated',
    'predict.related.numberOfFloors': 'Number of Floors',
    'predict.related.condition': 'Condition',
    'predict.related.areaBreakdown': 'Area Breakdown',
    'predict.related.excludingBasement': 'Excluding Basement',
    'predict.related.basementArea': 'Basement Area',
    'predict.related.totalLivingArea': 'Total Living Area',
    'predict.related.postRenovation': 'Post-Renovation',
    'predict.related.locationAmenities': 'Location & Amenities',
    'predict.related.nearbySchools': 'Nearby Schools',
    'predict.related.airportDistance': 'Airport Distance',
    'predict.related.postalCode': 'Postal Code',
    'predict.related.yes': 'Yes',
    'predict.related.no': 'No',
    'predict.related.viewsFeatures': 'Views & Features',
    'predict.related.numberOfViews': 'Number of Views',
    'predict.related.propertyId': 'Property ID',
    'predict.related.qualityIndicators': 'Quality Indicators',
    'predict.related.greatViews': 'Great Views',
    'predict.related.newBuild': 'New Build',
    'predict.related.propertyInsights': 'Property Insights',
    'predict.related.lotCoverage': 'Lot Coverage',
    'predict.related.sqFtPerBedroom': 'Sq Ft per Bedroom',
    'predict.related.cadPerSqFt': 'CAD per Sq Ft',
    
    // Heatmap Page
    'heatmap.title': 'Property Price Heatmap',
    'heatmap.subtitle': 'Visualize property prices across different locations',
    'heatmap.legend': 'Price Range',
    'heatmap.low': 'Low',
    'heatmap.medium': 'Medium',
    'heatmap.high': 'High',
    'heatmap.premium': 'Premium',
    
    // Chatbot
    'chatbot.title': 'AI Property Assistant',
    'chatbot.subtitle': 'Get instant property valuations, smart recommendations, and expert investment advice',
    'chatbot.placeholder': 'Tell me what you\'re looking for... (e.g., \'3 bedroom under 600k\' or \'waterfront with good views\')',
    'chatbot.voiceHint': 'Click the mic to use voice input',
    'chatbot.quickActions': 'Popular searches to get you started:',
    'chatbot.listening': 'Listening...',
    'chatbot.voiceComplete': 'Voice Input Complete',
    'chatbot.speakNow': 'Speak now...',
    'chatbot.thinking': 'AI is thinking',
    'chatbot.propertyResults': 'Property Results',
    'chatbot.noProperties': 'No properties yet',
    'chatbot.tryAsking': 'Try asking:',
    'chatbot.selectedProperty': 'Selected Property Details',
    'chatbot.askAI': 'Ask AI about this property',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome back',
    'dashboard.recentPredictions': 'Recent Predictions',
    'dashboard.favorites': 'Your Favorites',
    'dashboard.marketTrends': 'Market Trends',
    'dashboard.quickActions': 'Quick Actions',
    
    // Common
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.bedrooms': 'Bedrooms',
    'common.bathrooms': 'Bathrooms',
    'common.sqft': 'sq ft',
    'common.price': 'Price',
    'common.location': 'Location',
    'common.waterfront': 'Waterfront',
    'common.grade': 'Grade',
    'common.condition': 'Condition',
    'common.builtYear': 'Built Year',
    'common.confidence': 'Confidence',
    'common.features': 'Features',
    'common.detected': 'detected',
    'common.beds': 'beds',
    'common.baths': 'baths',
    
    // Footer
    'footer.description': 'AI-powered real estate platform for accurate property valuations',
    'footer.quickLinks': 'Quick Links',
    'footer.features': 'Features',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.contact': 'Contact Us',
    'footer.help': 'Help Center',
    'footer.rights': 'All rights reserved',
  },
  
  hi: {
    // Navigation
    'nav.home': 'होम',
    'nav.predict': 'भविष्यवाणी',
    'nav.analytics': 'विश्लेषण',
    'nav.heatmap': 'हीटमैप',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.favorites': 'पसंदीदा',
    'nav.chatbot': 'AI सहायक',
    'nav.profile': 'प्रोफाइल',
    'nav.signIn': 'साइन इन',
    'nav.signUp': 'साइन अप',
    'nav.signOut': 'साइन आउट',
    
    // Landing Page
    'landing.title': 'वैल्यू होम विज़न',
    'landing.subtitle': 'AI-संचालित रियल एस्टेट मूल्य भविष्यवाणी',
    'landing.description': '95.97% सटीकता के साथ उन्नत मशीन लर्निंग का उपयोग करके सटीक संपत्ति मूल्यांकन प्राप्त करें',
    'landing.features.title': 'हमारे प्लेटफॉर्म को क्यों चुनें?',
    'landing.features.accuracy': 'ML सटीकता',
    'landing.features.properties': 'संपत्तियों का विश्लेषण',
    'landing.features.predictions': 'भविष्यवाणियाँ की गईं',
    'landing.features.satisfaction': 'उपयोगकर्ता संतुष्टि',
    'landing.getStarted': 'शुरू करें',
    'landing.learnMore': 'और जानें',
    
    // Prediction Page
    'predict.title': 'संपत्ति मूल्य भविष्यवाणी',
    'predict.subtitle': 'हमारे उन्नत AI मॉडल का उपयोग करके तत्काल संपत्ति मूल्यांकन प्राप्त करें',
    'predict.form.title': 'संपत्ति विवरण',
    'predict.form.livingArea': 'रहने का क्षेत्र (वर्ग फुट)',
    'predict.form.lotArea': 'लॉट क्षेत्र (वर्ग फुट)',
    'predict.form.bedrooms': 'शयनकक्षों की संख्या',
    'predict.form.bathrooms': 'बाथरूम की संख्या',
    'predict.form.grade': 'घर का ग्रेड (1-13)',
    'predict.form.condition': 'घर की स्थिति (1-5)',
    'predict.form.builtYear': 'निर्माण वर्ष',
    'predict.form.location': 'स्थान चुनें',
    'predict.form.predict': 'मूल्य की भविष्यवाणी करें',
    'predict.form.predicting': 'भविष्यवाणी कर रहे हैं...',
    'predict.results.title': 'अनुमानित मूल्य',
    'predict.results.confidence': 'विश्वास',
    'predict.results.modelAccuracy': 'मॉडल सटीकता',
    'predict.results.analysis': 'बाजार विश्लेषण',
    'predict.form.dimensions': 'संपत्ति आयाम',
    'predict.form.rooms': 'कमरे की संरचना',
    'predict.form.quality': 'गुणवत्ता और स्थिति',
    'predict.form.history': 'संपत्ति इतिहास',
    'predict.form.locationDetails': 'स्थान विवरण',
    'predict.form.features': 'विशेष सुविधाएं',
    'predict.form.neighborhood': 'पड़ोस और पहुंच',
    'predict.form.quickStart': 'त्वरित प्रारंभ प्रीसेट',
    'predict.form.budgetHome': 'बजट घर',
    'predict.form.averageHome': 'औसत घर',
    'predict.form.luxuryEstate': 'लक्जरी संपदा',
    'predict.form.aiValuation': 'AI संपत्ति मूल्यांकन',
    'predict.form.featuresCount': 'विशेषताएं',
    'predict.form.submitPoweredBy': 'XGBoost ML के साथ 95.97% सटीकता • सेकंड में परिणाम',
    'predict.form.generateValuation': 'AI संपत्ति मूल्यांकन उत्पन्न करें',
    'predict.results.estimatedValue': 'अनुमानित संपत्ति मूल्य',
    'predict.results.marketAnalysis': 'बाजार विश्लेषण',
    'predict.results.keyInsights': 'मुख्य अंतर्दृष्टि',
    'predict.results.investmentCalculator': 'निवेश कैलकुलेटर',
    'predict.results.downPayment': 'डाउन पेमेंट',
    'predict.results.monthlyMortgage': 'मासिक बंधक (अनुमानित)',
    'predict.results.aiInsights': 'AI अंतर्दृष्टि और संपत्तियों की तुलना करें',
    'predict.results.chatAboutProperty': 'इस संपत्ति के बारे में चैट करें',
    
    // Analytics Page
    'analytics.title': 'बाजार विश्लेषण',
    'analytics.subtitle': 'व्यापक रियल एस्टेट बाजार अंतर्दृष्टि और रुझान',
    'analytics.investmentDashboard': 'निवेश विश्लेषण डैशबोर्ड',
    'analytics.roiCalculator': 'ROI कैलकुलेटर',
    'analytics.rentalAnalyzer': 'किराया आय विश्लेषक',
    'analytics.emiCalculator': 'EMI कैलकुलेटर',
    'analytics.comparison': 'तुलना',
    'analytics.purchasePrice': 'खरीद मूल्य (CAD)',
    'analytics.loanAmount': 'ऋण राशि (CAD)',
    'analytics.interestRate': 'ब्याज दर (%)',
    'analytics.loanTenure': 'ऋण अवधि (वर्ष)',
    'analytics.monthlyRent': 'अपेक्षित मासिक किराया (CAD)',
    'analytics.appreciation': 'वार्षिक वृद्धि (%)',
    
    // Analytics page missing keys  
    'analytics.dashboardSubtitle': 'संपत्ति निवेश विश्लेषण और ROI प्रक्षेपण',
    'analytics.currentlyAnalyzing': 'वर्तमान में विश्लेषण कर रहे हैं',
    'analytics.propertyNumber': 'संपत्ति',
    'analytics.sqft': 'वर्ग फुट',
    'analytics.grade': 'ग्रेड',
    'analytics.clearSelection': 'चयन साफ़ करें',
    'analytics.roiProjection': '10व ROI',
    'analytics.rentalYield': 'किराया उपज',
    'analytics.monthlyEmi': 'मासिक EMI',
    'analytics.totalInterest': 'कुल ब्याज',
    'analytics.projectionBased': 'प्रशंसा पर आधारित प्रक्षेपण',
    'analytics.annualRentVs': 'वार्षिक किराया बनाम संपत्ति मूल्य',
    'analytics.basedOnRateAndTenure': 'दर और कार्यकाल पर आधारित',
    'analytics.overFullLoanTenure': 'पूर्ण ऋण कार्यकाल में',
    'analytics.roi': 'ROI',
    'analytics.rental': 'किराया',
    'analytics.emi': 'EMI',
    'analytics.compare': 'तुलना',
    'analytics.configureInvestmentParameters': 'निवेश पैरामीटर कॉन्फ़िगर करें',
    'analytics.investmentCalculator': 'निवेश कैलकुलेटर',
    
    // Heatmap Page
    'heatmap.title': 'संपत्ति मूल्य हीटमैप',
    'heatmap.subtitle': 'विभिन्न स्थानों में संपत्ति की कीमतों को देखें',
    'heatmap.legend': 'मूल्य सीमा',
    'heatmap.low': 'कम',
    'heatmap.medium': 'मध्यम',
    'heatmap.high': 'उच्च',
    'heatmap.premium': 'प्रीमियम',
    
    // Chatbot
    'chatbot.title': 'AI संपत्ति सहायक',
    'chatbot.subtitle': 'तत्काल संपत्ति मूल्यांकन, स्मार्ट सिफारिशें और विशेषज्ञ निवेश सलाह प्राप्त करें',
    'chatbot.placeholder': 'मुझे बताएं कि आप क्या खोज रहे हैं... (जैसे \'600k के तहत 3 बेडरूम\' या \'अच्छे दृश्यों के साथ वाटरफ्रंट\')',
    'chatbot.voiceHint': 'वॉयस इनपुट का उपयोग करने के लिए माइक पर क्लिक करें',
    'chatbot.quickActions': 'शुरू करने के लिए लोकप्रिय खोजें:',
    'chatbot.listening': 'सुन रहे हैं...',
    'chatbot.voiceComplete': 'वॉयस इनपुट पूरा',
    'chatbot.speakNow': 'अब बोलें...',
    'chatbot.thinking': 'AI सोच रहा है',
    'chatbot.propertyResults': 'संपत्ति परिणाम',
    'chatbot.noProperties': 'अभी तक कोई संपत्ति नहीं',
    'chatbot.tryAsking': 'पूछने की कोशिश करें:',
    'chatbot.selectedProperty': 'चयनित संपत्ति विवरण',
    'chatbot.askAI': 'इस संपत्ति के बारे में AI से पूछें',
    
    // Common
    'common.bedrooms': 'शयनकक्ष',
    'common.bathrooms': 'बाथरूम',
    'common.sqft': 'वर्ग फुट',
    'common.price': 'मूल्य',
    'common.location': 'स्थान',
    'common.waterfront': 'वाटरफ्रंट',
    'common.grade': 'ग्रेड',
    'common.condition': 'स्थिति',
    'common.builtYear': 'निर्माण वर्ष',
    'common.confidence': 'विश्वास',
    'common.features': 'विशेषताएं',
    'common.detected': 'का पता लगाया गया',
    'common.beds': 'बेड',
    'common.baths': 'बाथ',
  },
  
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.predict': 'Predecir',
    'nav.analytics': 'Análisis',
    'nav.heatmap': 'Mapa de Calor',
    'nav.dashboard': 'Panel',
    'nav.favorites': 'Favoritos',
    'nav.chatbot': 'Asistente IA',
    'nav.profile': 'Perfil',
    'nav.signIn': 'Iniciar Sesión',
    'nav.signUp': 'Registrarse',
    'nav.signOut': 'Cerrar Sesión',
    
    // Landing Page
    'landing.title': 'Value Home Vision',
    'landing.subtitle': 'Predicción de Precios Inmobiliarios con IA',
    'landing.description': 'Obtenga valuaciones precisas de propiedades usando aprendizaje automático avanzado con 95.97% de precisión',
    'landing.features.title': '¿Por qué elegir nuestra plataforma?',
    'landing.features.accuracy': 'Precisión ML',
    'landing.features.properties': 'Propiedades Analizadas',
    'landing.features.predictions': 'Predicciones Realizadas',
    'landing.features.satisfaction': 'Satisfacción del Usuario',
    'landing.getStarted': 'Comenzar',
    'landing.learnMore': 'Aprender Más',
    
    // Prediction Page
    'predict.title': 'Predicción de Precio de Propiedad',
    'predict.subtitle': 'Obtenga valuación instantánea de propiedad usando nuestro modelo avanzado de IA',
    'predict.form.title': 'Detalles de la Propiedad',
    'predict.form.livingArea': 'Área Habitable (pies²)',
    'predict.form.lotArea': 'Área del Lote (pies²)',
    'predict.form.bedrooms': 'Número de Dormitorios',
    'predict.form.bathrooms': 'Número de Baños',
    'predict.form.grade': 'Grado de la Casa (1-13)',
    'predict.form.condition': 'Condición de la Casa (1-5)',
    'predict.form.builtYear': 'Año de Construcción',
    'predict.form.location': 'Seleccionar Ubicación',
    'predict.form.predict': 'Predecir Precio',
    'predict.form.predicting': 'Prediciendo...',
    'predict.form.areaExcludingBasement': 'Área Excluyendo Sótano (pies²)',
    'predict.form.areaOfBasement': 'Área del Sótano (pies²)',
    'predict.form.postalCode': 'Código Postal',
    'predict.form.latitude': 'Latitud',
    'predict.form.longitude': 'Longitud',
    'predict.form.views': 'Número de Vistas',
    'predict.form.waterfront': 'Propiedad Frente al Agua',
    'predict.form.renovationYear': 'Año de Renovación',
    'predict.form.schoolsNearby': 'Escuelas Cercanas',
    'predict.form.distanceFromAirport': 'Distancia del Aeropuerto (km)',
    'predict.form.dimensions': 'Dimensiones de la Propiedad',
    'predict.form.rooms': 'Configuración de Habitaciones',
    'predict.form.quality': 'Calidad y Condición',
    'predict.form.history': 'Historia de la Propiedad',
    'predict.form.locationDetails': 'Detalles de Ubicación',
    'predict.form.features': 'Características Especiales',
    'predict.form.neighborhood': 'Vecindario y Accesibilidad',
    'predict.form.quickStart': 'Presets de Inicio Rápido',
    'predict.form.budgetHome': 'Casa Económica',
    'predict.form.averageHome': 'Casa Promedio',
    'predict.form.luxuryEstate': 'Propiedad de Lujo',
    'predict.form.aiValuation': 'Valuación IA de Propiedad',
    'predict.form.poweredBy': 'Impulsado por modelo ML XGBoost de 25 características',
    'predict.form.accuracy': 'Precisión',
    'predict.form.featuresCount': 'Características',
    'predict.form.properties': 'Propiedades',
    'predict.form.submitPoweredBy': 'Potenciado por XGBoost ML con 95.97% de precisión • Resultados en segundos',
    'predict.form.generateValuation': 'Generar Valuación AI de Propiedad',
    'predict.results.title': 'Valor Predicho',
    'predict.results.confidence': 'Confianza',
    'predict.results.modelAccuracy': 'Precisión del Modelo',
    'predict.results.analysis': 'Análisis de Mercado',
    'predict.results.estimatedValue': 'Valor Estimado de la Propiedad',
    'predict.results.marketAnalysis': 'Análisis de Mercado',
    'predict.results.keyInsights': 'Perspectivas Clave',
    'predict.results.investmentCalculator': 'Calculadora de Inversión',
    'predict.results.propertyLocation': 'Ubicación de la Propiedad',
    'predict.results.downPayment': 'Pago Inicial',
    'predict.results.monthlyMortgage': 'Hipoteca Mensual (Est.)',
    'predict.results.coordinates': 'Coordenadas',
    'predict.results.priceRange': 'Rango de Precios',
    'predict.results.locationRating': 'Calificación de Ubicación',
    'predict.results.propertyGrade': 'Grado de la Propiedad',
    'predict.results.investmentAdvice': 'Consejo de Inversión',
    'predict.results.sizeFactor': 'Factor de Tamaño',
    'predict.results.locationPremium': 'Prima de Ubicación',
    'predict.results.predictionAccuracy': 'Precisión de Predicción',
    'predict.results.keyValueDrivers': 'Factores Clave de Valor',
    'predict.results.aiInsights': 'Obtener Perspectivas IA y Comparar Propiedades',
    'predict.results.aiInsightsDesc': 'Haga preguntas a nuestro asistente IA sobre esta predicción, compare con propiedades similares, u obtenga consejos de inversión basados en sus necesidades específicas.',
    'predict.results.chatAboutProperty': 'Chatear Sobre Esta Propiedad',
    'predict.results.relatedProperties': 'Propiedades Relacionadas y Ubicación en Mapa',
    'predict.results.similarProperties': 'Propiedades Similares Encontradas',
    'predict.results.mapLocation': 'Ubicación en Mapa',
    'predict.results.viewDetails': 'Ver Detalles',
    
    // Analytics Page
    'analytics.title': 'Análisis de Mercado',
    'analytics.subtitle': 'Información integral del mercado inmobiliario y tendencias',
    'analytics.overview': 'Resumen del Mercado',
    'analytics.trends': 'Tendencias de Precios',
    'analytics.distribution': 'Distribución de Precios',
    'analytics.investment': 'Calculadora de Inversión',
    'analytics.roi': 'Análisis ROI',
    'analytics.rental': 'Alquiler',
    'analytics.emi': 'EMI',
    'analytics.compare': 'Comparar',
    'analytics.investmentDashboard': 'Panel de Análisis de Inversión',
    'analytics.dashboardSubtitle': 'Tome decisiones inmobiliarias basadas en datos con perspectivas de ROI, alquiler y EMI.',
    'analytics.currentlyAnalyzing': 'Analizando Actualmente',
    'analytics.clearSelection': 'Limpiar Selección',
    'analytics.roiProjection': 'ROI 10A',
    'analytics.rentalYield': 'Rendimiento de Alquiler',
    'analytics.monthlyEmi': 'EMI Mensual',
    'analytics.totalInterest': 'Interés Total',
    'analytics.projectionBased': 'Proyección basada en apreciación',
    'analytics.annualRentVs': 'Alquiler anual vs. valor de propiedad',
    'analytics.basedOnRate': 'Basado en tasa y plazo',
    'analytics.overFullTenure': 'Durante todo el plazo del préstamo',
    'analytics.roiCalculator': 'Calculadora ROI',
    'analytics.rentalAnalyzer': 'Analizador de Ingresos de Alquiler',
    'analytics.emiCalculator': 'Calculadora EMI',
    'analytics.comparison': 'Comparar',
    'analytics.purchasePrice': 'Precio de Compra (CAD)',
    'analytics.loanAmount': 'Monto del Préstamo (CAD)',
    'analytics.interestRate': 'Tasa de Interés (%)',
    'analytics.loanTenure': 'Plazo del Préstamo (Años)',
    'analytics.monthlyRent': 'Alquiler Mensual Esperado (CAD)',
    'analytics.appreciation': 'Apreciación Anual (%)',
    'analytics.investmentSummary': 'Resumen de Inversión',
    'analytics.projectedValue': 'Valor Proyectado (10A)',
    'analytics.totalGains': 'Ganancias Totales de Capital',
    'analytics.returnOnInvestment': 'Retorno de Inversión',
    'analytics.cashFlow': 'Flujo de Caja Mensual',
    'analytics.breakEven': 'Período de Equilibrio',
    'analytics.rentalSummary': 'Análisis de Ingresos de Alquiler',
    'analytics.grossYield': 'Rendimiento Bruto de Alquiler',
    'analytics.monthlyIncome': 'Ingresos Mensuales de Alquiler',
    'analytics.annualIncome': 'Ingresos Anuales de Alquiler',
    'analytics.tenYearIncome': 'Ingresos de Alquiler de 10 Años',
    'analytics.emiBreakdown': 'Desglose EMI',
    'analytics.principalVsInterest': 'Principal vs Interés',
    'analytics.paymentSchedule': 'Calendario de Pagos en el Tiempo',
    
    // Additional Spanish Analytics Keys
    'analytics.propertyNumber': 'Propiedad',
    'analytics.sqft': 'pies²',
    'analytics.grade': 'Grado',
    'analytics.configureInvestmentParameters': 'Configurar parámetros de inversión',
    'analytics.investmentCalculator': 'Calculadora de Inversión',
    'analytics.basedOnRateAndTenure': 'Basado en tasa y plazo',
    'analytics.overFullLoanTenure': 'Durante todo el plazo del préstamo',
    
    // Predict Related Properties
    'predict.related.title': 'Propiedades Relacionadas',
    'predict.related.mapLocation': 'Ubicación en Mapa',
    'predict.related.similarProperties': 'Propiedades Similares Encontradas',
    'predict.related.match': 'coincidencia',
    'predict.related.beds': 'dorm',
    'predict.related.baths': 'baños',
    'predict.related.sqft': 'pies²',
    'predict.related.grade': 'Grado',
    'predict.related.waterfront': 'Frente al Agua',
    'predict.related.viewOnMap': 'Ver en mapa',
    'predict.related.viewDetails': 'Ver Detalles',
    'predict.related.propertyDetails': 'Detalles de la Propiedad',
    'predict.related.gradeLuxury': 'Lujo',
    'predict.related.gradeExcellent': 'Excelente',
    'predict.related.gradeVeryGood': 'Muy Bueno',
    'predict.related.gradeGood': 'Bueno',
    'predict.related.gradeAverage': 'Promedio',
    'predict.related.gradeBelowAverage': 'Bajo el Promedio',
    'predict.related.conditionExcellent': 'Excelente',
    'predict.related.conditionVeryGood': 'Muy Bueno',
    'predict.related.conditionGood': 'Bueno',
    'predict.related.conditionFair': 'Regular',
    'predict.related.conditionPoor': 'Malo',
    'predict.related.bedrooms': 'Dormitorios',
    'predict.related.bathrooms': 'Baños',
    'predict.related.livingArea': 'Área Habitable (pies²)',
    'predict.related.lotSize': 'Tamaño del Lote (pies²)',
    'predict.related.buildingInfo': 'Información del Edificio',
    'predict.related.builtYear': 'Año de Construcción',
    'predict.related.yearsOld': 'años de antigüedad',
    'predict.related.renovated': 'Renovado',
    'predict.related.numberOfFloors': 'Número de Pisos',
    'predict.related.condition': 'Condición',
    'predict.related.areaBreakdown': 'Desglose de Área',
    'predict.related.excludingBasement': 'Excluyendo Sótano',
    'predict.related.basementArea': 'Área del Sótano',
    'predict.related.totalLivingArea': 'Área Total Habitable',
    'predict.related.postRenovation': 'Post-Renovación',
    'predict.related.locationAmenities': 'Ubicación y Comodidades',
    'predict.related.nearbySchools': 'Escuelas Cercanas',
    'predict.related.airportDistance': 'Distancia al Aeropuerto',
    'predict.related.postalCode': 'Código Postal',
    'predict.related.yes': 'Sí',
    'predict.related.no': 'No',
    'predict.related.viewsFeatures': 'Vistas y Características',
    'predict.related.numberOfViews': 'Número de Vistas',
    'predict.related.propertyId': 'ID de Propiedad',
    'predict.related.qualityIndicators': 'Indicadores de Calidad',
    'predict.related.greatViews': 'Excelentes Vistas',
    'predict.related.newBuild': 'Nueva Construcción',
    'predict.related.propertyInsights': 'Perspectivas de la Propiedad',
    'predict.related.lotCoverage': 'Cobertura del Lote',
    'predict.related.sqFtPerBedroom': 'Pies² por Dormitorio',
    'predict.related.cadPerSqFt': 'CAD por Pies²',
    
    // Heatmap Page
    'heatmap.title': 'Mapa de Calor de Precios de Propiedades',
    'heatmap.subtitle': 'Visualice precios de propiedades en diferentes ubicaciones',
    'heatmap.legend': 'Rango de Precios',
    'heatmap.low': 'Bajo',
    'heatmap.medium': 'Medio',
    'heatmap.high': 'Alto',
    'heatmap.premium': 'Premium',
    
    // Chatbot
    'chatbot.title': 'Asistente de Propiedades IA',
    'chatbot.subtitle': 'Obtenga valuaciones instantáneas de propiedades, recomendaciones inteligentes y asesoramiento experto en inversiones',
    'chatbot.placeholder': 'Dígame qué está buscando... (ej. \'3 dormitorios bajo 600k\' o \'frente al agua con buenas vistas\')',
    'chatbot.voiceHint': 'Haga clic en el micrófono para usar entrada de voz',
    'chatbot.quickActions': 'Búsquedas populares para comenzar:',
    'chatbot.listening': 'Escuchando...',
    'chatbot.voiceComplete': 'Entrada de Voz Completa',
    'chatbot.speakNow': 'Hable ahora...',
    'chatbot.thinking': 'IA está pensando',
    'chatbot.propertyResults': 'Resultados de Propiedades',
    'chatbot.noProperties': 'Aún no hay propiedades',
    'chatbot.tryAsking': 'Intente preguntar:',
    'chatbot.selectedProperty': 'Detalles de Propiedad Seleccionada',
    'chatbot.askAI': 'Preguntar a IA sobre esta propiedad',
    
    // Dashboard
    'dashboard.title': 'Panel de Control',
    'dashboard.welcome': 'Bienvenido de vuelta',
    'dashboard.recentPredictions': 'Predicciones Recientes',
    'dashboard.favorites': 'Sus Favoritos',
    'dashboard.marketTrends': 'Tendencias del Mercado',
    'dashboard.quickActions': 'Acciones Rápidas',
    
    // Common
    'common.search': 'Buscar',
    'common.filter': 'Filtro',
    'common.sort': 'Ordenar',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.bedrooms': 'Dormitorios',
    'common.bathrooms': 'Baños',
    'common.sqft': 'pies²',
    'common.price': 'Precio',
    'common.location': 'Ubicación',
    'common.waterfront': 'Frente al Agua',
    'common.grade': 'Grado',
    'common.condition': 'Condición',
    'common.builtYear': 'Año de Construcción',
    'common.confidence': 'Confianza',
    'common.features': 'Características',
    'common.detected': 'detectado',
    'common.beds': 'dorm',
    'common.baths': 'baños',
    
    // Footer
    'footer.description': 'Plataforma inmobiliaria impulsada por IA para valuaciones precisas de propiedades',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.features': 'Características',
    'footer.support': 'Soporte',
    'footer.legal': 'Legal',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    'footer.contact': 'Contáctanos',
    'footer.help': 'Centro de Ayuda',
    'footer.rights': 'Todos los derechos reservados',
  },
  
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.predict': 'Prédire',
    'nav.analytics': 'Analytique',
    'nav.heatmap': 'Carte de Chaleur',
    'nav.dashboard': 'Tableau de Bord',
    'nav.favorites': 'Favoris',
    'nav.chatbot': 'Assistant IA',
    'nav.profile': 'Profil',
    'nav.signIn': 'Se Connecter',
    'nav.signUp': 'S\'inscrire',
    'nav.signOut': 'Se Déconnecter',
    
    // Landing Page
    'landing.title': 'Value Home Vision',
    'landing.subtitle': 'Prédiction de Prix Immobilier Alimentée par IA',
    'landing.description': 'Obtenez des évaluations précises de propriétés en utilisant l\'apprentissage automatique avancé avec 95.97% de précision',
    'landing.features.title': 'Pourquoi choisir notre plateforme ?',
    'landing.features.accuracy': 'Précision ML',
    'landing.features.properties': 'Propriétés Analysées',
    'landing.features.predictions': 'Prédictions Faites',
    'landing.features.satisfaction': 'Satisfaction Utilisateur',
    'landing.getStarted': 'Commencer',
    'landing.learnMore': 'En Savoir Plus',
    
    // Prediction Page
    'predict.title': 'Prédiction de Prix de Propriété',
    'predict.subtitle': 'Obtenez une évaluation instantanée de propriété en utilisant notre modèle IA avancé',
    'predict.form.title': 'Détails de la Propriété',
    'predict.form.livingArea': 'Surface Habitable (pieds²)',
    'predict.form.lotArea': 'Surface du Terrain (pieds²)',
    'predict.form.bedrooms': 'Nombre de Chambres',
    'predict.form.bathrooms': 'Nombre de Salles de Bain',
    'predict.form.grade': 'Grade de la Maison (1-13)',
    'predict.form.condition': 'Condition de la Maison (1-5)',
    'predict.form.builtYear': 'Année de Construction',
    'predict.form.location': 'Sélectionner l\'Emplacement',
    'predict.form.predict': 'Prédire le Prix',
    'predict.form.predicting': 'Prédiction...',
    'predict.form.areaExcludingBasement': 'Surface Hors Sous-sol (pieds²)',
    'predict.form.areaOfBasement': 'Surface du Sous-sol (pieds²)',
    'predict.form.postalCode': 'Code Postal',
    'predict.form.latitude': 'Latitude',
    'predict.form.longitude': 'Longitude',
    'predict.form.views': 'Nombre de Vues',
    'predict.form.waterfront': 'Propriété en Bord de Mer',
    'predict.form.renovationYear': 'Année de Rénovation',
    'predict.form.schoolsNearby': 'Écoles à Proximité',
    'predict.form.distanceFromAirport': 'Distance de l\'Aéroport (km)',
    'predict.form.dimensions': 'Dimensions de la Propriété',
    'predict.form.rooms': 'Configuration des Pièces',
    'predict.form.quality': 'Qualité et Condition',
    'predict.form.history': 'Historique de la Propriété',
    'predict.form.locationDetails': 'Détails de l\'Emplacement',
    'predict.form.features': 'Caractéristiques Spéciales',
    'predict.form.neighborhood': 'Quartier et Accessibilité',
    'predict.form.quickStart': 'Préréglages de Démarrage Rapide',
    'predict.form.budgetHome': 'Maison Économique',
    'predict.form.averageHome': 'Maison Moyenne',
    'predict.form.luxuryEstate': 'Propriété de Luxe',
    'predict.form.aiValuation': 'Évaluation IA de Propriété',
    'predict.form.poweredBy': 'Alimenté par un modèle ML XGBoost à 25 caractéristiques',
    'predict.form.accuracy': 'Précision',
    'predict.form.featuresCount': 'Caractéristiques',
    'predict.form.properties': 'Propriétés',
    'predict.form.submitPoweredBy': 'Alimenté par XGBoost ML avec 95.97% de précision • Résultats en secondes',
    'predict.form.generateValuation': 'Générer une Évaluation IA de Propriété',
    'predict.results.title': 'Valeur Prédite',
    'predict.results.confidence': 'Confiance',
    'predict.results.modelAccuracy': 'Précision du Modèle',
    'predict.results.analysis': 'Analyse de Marché',
    'predict.results.estimatedValue': 'Valeur Estimée de la Propriété',
    'predict.results.marketAnalysis': 'Analyse de Marché',
    'predict.results.keyInsights': 'Aperçus Clés',
    'predict.results.investmentCalculator': 'Calculateur d\'Investissement',
    'predict.results.propertyLocation': 'Emplacement de la Propriété',
    'predict.results.downPayment': 'Acompte',
    'predict.results.monthlyMortgage': 'Hypothèque Mensuelle (Est.)',
    'predict.results.coordinates': 'Coordonnées',
    'predict.results.priceRange': 'Gamme de Prix',
    'predict.results.locationRating': 'Évaluation de l\'Emplacement',
    'predict.results.propertyGrade': 'Grade de la Propriété',
    'predict.results.investmentAdvice': 'Conseil d\'Investissement',
    'predict.results.sizeFactor': 'Facteur de Taille',
    'predict.results.locationPremium': 'Prime d\'Emplacement',
    'predict.results.predictionAccuracy': 'Précision de la Prédiction',
    'predict.results.keyValueDrivers': 'Facteurs Clés de Valeur',
    'predict.results.aiInsights': 'Obtenir des Aperçus IA et Comparer les Propriétés',
    'predict.results.aiInsightsDesc': 'Posez des questions à notre assistant IA sur cette prédiction, comparez avec des propriétés similaires, ou obtenez des conseils d\'investissement basés sur vos besoins spécifiques.',
    'predict.results.chatAboutProperty': 'Discuter de Cette Propriété',
    'predict.results.relatedProperties': 'Propriétés Connexes et Emplacement sur la Carte',
    'predict.results.similarProperties': 'Propriétés Similaires Trouvées',
    'predict.results.mapLocation': 'Emplacement sur la Carte',
    'predict.results.viewDetails': 'Voir les Détails',
    
    // Analytics Page
    'analytics.title': 'Analytique de Marché',
    'analytics.subtitle': 'Aperçus complets du marché immobilier et tendances',
    'analytics.overview': 'Aperçu du Marché',
    'analytics.trends': 'Tendances des Prix',
    'analytics.distribution': 'Distribution des Prix',
    'analytics.investment': 'Calculateur d\'Investissement',
    'analytics.roi': 'Analyse ROI',
    'analytics.rental': 'Location',
    'analytics.emi': 'EMI',
    'analytics.compare': 'Comparer',
    'analytics.investmentDashboard': 'Tableau de Bord d\'Analyse d\'Investissement',
    'analytics.dashboardSubtitle': 'Prenez des décisions immobilières basées sur les données avec des aperçus ROI, location et EMI.',
    'analytics.currentlyAnalyzing': 'Analyse en Cours',
    'analytics.clearSelection': 'Effacer la Sélection',
    'analytics.roiProjection': 'ROI 10A',
    'analytics.rentalYield': 'Rendement Locatif',
    'analytics.monthlyEmi': 'EMI Mensuel',
    'analytics.totalInterest': 'Intérêt Total',
    'analytics.projectionBased': 'Projection basée sur l\'appréciation',
    'analytics.annualRentVs': 'Loyer annuel vs. valeur de propriété',
    'analytics.basedOnRate': 'Basé sur le taux et la durée',
    'analytics.overFullTenure': 'Sur toute la durée du prêt',
    'analytics.roiCalculator': 'Calculateur ROI',
    'analytics.rentalAnalyzer': 'Analyseur de Revenus Locatifs',
    'analytics.emiCalculator': 'Calculateur EMI',
    'analytics.comparison': 'Comparer',
    'analytics.purchasePrice': 'Prix d\'Achat (CAD)',
    'analytics.loanAmount': 'Montant du Prêt (CAD)',
    'analytics.interestRate': 'Taux d\'Intérêt (%)',
    'analytics.loanTenure': 'Durée du Prêt (Années)',
    'analytics.monthlyRent': 'Loyer Mensuel Attendu (CAD)',
    'analytics.appreciation': 'Appréciation Annuelle (%)',
    'analytics.investmentSummary': 'Résumé d\'Investissement',
    'analytics.projectedValue': 'Valeur Projetée (10A)',
    'analytics.totalGains': 'Gains Totaux en Capital',
    'analytics.returnOnInvestment': 'Retour sur Investissement',
    'analytics.cashFlow': 'Flux de Trésorerie Mensuel',
    'analytics.breakEven': 'Période d\'Équilibre',
    'analytics.rentalSummary': 'Analyse des Revenus Locatifs',
    'analytics.grossYield': 'Rendement Locatif Brut',
    'analytics.monthlyIncome': 'Revenus Locatifs Mensuels',
    'analytics.annualIncome': 'Revenus Locatifs Annuels',
    'analytics.tenYearIncome': 'Revenus Locatifs sur 10 Ans',
    'analytics.emiBreakdown': 'Répartition EMI',
    'analytics.principalVsInterest': 'Principal vs Intérêt',
    'analytics.paymentSchedule': 'Calendrier de Paiement dans le Temps',
    
    // Additional French Analytics Keys
    'analytics.propertyNumber': 'Propriété',
    'analytics.sqft': 'pieds²',
    'analytics.grade': 'Grade',
    'analytics.configureInvestmentParameters': 'Configurer les paramètres d\'investissement',
    'analytics.investmentCalculator': 'Calculateur d\'Investissement',
    'analytics.basedOnRateAndTenure': 'Basé sur le taux et la durée',
    'analytics.overFullLoanTenure': 'Sur toute la durée du prêt',
    
    // Predict Related Properties
    'predict.related.title': 'Propriétés Connexes',
    'predict.related.mapLocation': 'Emplacement sur la Carte',
    'predict.related.similarProperties': 'Propriétés Similaires Trouvées',
    'predict.related.match': 'correspondance',
    'predict.related.beds': 'lits',
    'predict.related.baths': 'bains',
    'predict.related.sqft': 'pieds²',
    'predict.related.grade': 'Grade',
    'predict.related.waterfront': 'Front de Mer',
    'predict.related.viewOnMap': 'Voir sur la carte',
    'predict.related.viewDetails': 'Voir les Détails',
    'predict.related.propertyDetails': 'Détails de la Propriété',
    'predict.related.gradeLuxury': 'Luxe',
    'predict.related.gradeExcellent': 'Excellent',
    'predict.related.gradeVeryGood': 'Très Bon',
    'predict.related.gradeGood': 'Bon',
    'predict.related.gradeAverage': 'Moyen',
    'predict.related.gradeBelowAverage': 'En Dessous de la Moyenne',
    'predict.related.conditionExcellent': 'Excellent',
    'predict.related.conditionVeryGood': 'Très Bon',
    'predict.related.conditionGood': 'Bon',
    'predict.related.conditionFair': 'Passable',
    'predict.related.conditionPoor': 'Mauvais',
    'predict.related.bedrooms': 'Chambres',
    'predict.related.bathrooms': 'Salles de Bain',
    'predict.related.livingArea': 'Surface Habitable (pieds²)',
    'predict.related.lotSize': 'Taille du Terrain (pieds²)',
    'predict.related.buildingInfo': 'Information du Bâtiment',
    'predict.related.builtYear': 'Année de Construction',
    'predict.related.yearsOld': 'ans',
    'predict.related.renovated': 'Rénové',
    'predict.related.numberOfFloors': 'Nombre d\'Étages',
    'predict.related.condition': 'Condition',
    'predict.related.areaBreakdown': 'Répartition des Surfaces',
    'predict.related.excludingBasement': 'Hors Sous-sol',
    'predict.related.basementArea': 'Surface du Sous-sol',
    'predict.related.totalLivingArea': 'Surface Habitable Totale',
    'predict.related.postRenovation': 'Post-Rénovation',
    'predict.related.locationAmenities': 'Emplacement et Commodités',
    'predict.related.nearbySchools': 'Écoles à Proximité',
    'predict.related.airportDistance': 'Distance de l\'Aéroport',
    'predict.related.postalCode': 'Code Postal',
    'predict.related.yes': 'Oui',
    'predict.related.no': 'Non',
    'predict.related.viewsFeatures': 'Vues et Caractéristiques',
    'predict.related.numberOfViews': 'Nombre de Vues',
    'predict.related.propertyId': 'ID de Propriété',
    'predict.related.qualityIndicators': 'Indicateurs de Qualité',
    'predict.related.greatViews': 'Belles Vues',
    'predict.related.newBuild': 'Nouvelle Construction',
    'predict.related.propertyInsights': 'Aperçus de la Propriété',
    'predict.related.lotCoverage': 'Couverture du Terrain',
    'predict.related.sqFtPerBedroom': 'Pieds² par Chambre',
    'predict.related.cadPerSqFt': 'CAD par Pieds²',
    
    // Heatmap Page
    'heatmap.title': 'Carte de Chaleur des Prix de Propriétés',
    'heatmap.subtitle': 'Visualisez les prix des propriétés dans différents emplacements',
    'heatmap.legend': 'Gamme de Prix',
    'heatmap.low': 'Bas',
    'heatmap.medium': 'Moyen',
    'heatmap.high': 'Élevé',
    'heatmap.premium': 'Premium',
    
    // Chatbot
    'chatbot.title': 'Assistant Propriétés IA',
    'chatbot.subtitle': 'Obtenez des évaluations instantanées de propriétés, des recommandations intelligentes et des conseils d\'investissement experts',
    'chatbot.placeholder': 'Dites-moi ce que vous cherchez... (ex. \'3 chambres sous 600k\' ou \'front de mer avec de belles vues\')',
    'chatbot.voiceHint': 'Cliquez sur le micro pour utiliser l\'entrée vocale',
    'chatbot.quickActions': 'Recherches populaires pour commencer :',
    'chatbot.listening': 'Écoute...',
    'chatbot.voiceComplete': 'Entrée Vocale Terminée',
    'chatbot.speakNow': 'Parlez maintenant...',
    'chatbot.thinking': 'IA réfléchit',
    'chatbot.propertyResults': 'Résultats de Propriétés',
    'chatbot.noProperties': 'Pas encore de propriétés',
    'chatbot.tryAsking': 'Essayez de demander :',
    'chatbot.selectedProperty': 'Détails de Propriété Sélectionnée',
    'chatbot.askAI': 'Demander à l\'IA sur cette propriété',
    
    // Dashboard
    'dashboard.title': 'Tableau de Bord',
    'dashboard.welcome': 'Bienvenue',
    'dashboard.recentPredictions': 'Prédictions Récentes',
    'dashboard.favorites': 'Vos Favoris',
    'dashboard.marketTrends': 'Tendances du Marché',
    'dashboard.quickActions': 'Actions Rapides',
    
    // Common
    'common.search': 'Rechercher',
    'common.filter': 'Filtre',
    'common.sort': 'Trier',
    'common.save': 'Sauvegarder',
    'common.cancel': 'Annuler',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.bedrooms': 'Chambres',
    'common.bathrooms': 'Salles de Bain',
    'common.sqft': 'pieds²',
    'common.price': 'Prix',
    'common.location': 'Emplacement',
    'common.waterfront': 'Front de Mer',
    'common.grade': 'Grade',
    'common.condition': 'Condition',
    'common.builtYear': 'Année de Construction',
    'common.confidence': 'Confiance',
    'common.features': 'Caractéristiques',
    'common.detected': 'détecté',
    'common.beds': 'lits',
    'common.baths': 'bains',
    
    // Footer
    'footer.description': 'Plateforme immobilière alimentée par IA pour des évaluations précises de propriétés',
    'footer.quickLinks': 'Liens Rapides',
    'footer.features': 'Caractéristiques',
    'footer.support': 'Support',
    'footer.legal': 'Légal',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': 'Conditions de Service',
    'footer.contact': 'Nous Contacter',
    'footer.help': 'Centre d\'Aide',
    'footer.rights': 'Tous droits réservés',
  },
  
  te: {
    // Navigation
    'nav.home': 'హోమ్',
    'nav.predict': 'అంచనా',
    'nav.analytics': 'విశ్లేషణలు',
    'nav.heatmap': 'హీట్‌మ్యాప్',
    'nav.dashboard': 'డాష్‌బోర్డ్',
    'nav.favorites': 'ఇష్టమైనవి',
    'nav.chatbot': 'AI సహాయకుడు',
    'nav.profile': 'ప్రొఫైల్',
    'nav.signIn': 'సైన్ ఇన్',
    'nav.signUp': 'సైన్ అప్',
    'nav.signOut': 'సైన్ అవుట్',
    
    // Landing Page
    'landing.title': 'వాల్యూ హోమ్ విజన్',
    'landing.subtitle': 'AI-ఆధారిత రియల్ ఎస్టేట్ ధర అంచనా',
    'landing.description': '95.97% ఖచ్చితత్వంతో అధునాతన మెషిన్ లెర్నింగ్ ఉపయోగించి ఖచ్చితమైన ఆస్తి మూల్యాంకనలను పొందండి',
    'landing.features.title': 'మా ప్లాట్‌ఫారమ్‌ను ఎందుకు ఎంచుకోవాలి?',
    'landing.features.accuracy': 'ML ఖచ్చితత్వం',
    'landing.features.properties': 'విశ్లేషించిన ఆస్తులు',
    'landing.features.predictions': 'చేసిన అంచనలు',
    'landing.features.satisfaction': 'వినియోగదారు సంతృప్తి',
    'landing.getStarted': 'ప్రారంభించండి',
    'landing.learnMore': 'మరింత తెలుసుకోండి',
    
    // Prediction Page
    'predict.title': 'ఆస్తి ధర అంచనా',
    'predict.subtitle': 'మా అధునాతన AI మోడల్ ఉపయోగించి తక్షణ ఆస్తి మూల్యాంకనం పొందండి',
    'predict.form.title': 'ఆస్తి వివరాలు',
    'predict.form.livingArea': 'నివాస వైశాల్యం (చ.అడుగులు)',
    'predict.form.lotArea': 'లాట్ వైశాల్యం (చ.అడుగులు)',
    'predict.form.bedrooms': 'పడకగదుల సంఖ్య',
    'predict.form.bathrooms': 'స్నానపు గదుల సంఖ్య',
    'predict.form.grade': 'ఇంటి గ్రేడ్ (1-13)',
    'predict.form.condition': 'ఇంటి స్థితి (1-5)',
    'predict.form.builtYear': 'నిర్మాణ సంవత్సరం',
    'predict.form.location': 'స్థానం ఎంచుకోండి',
    'predict.form.predict': 'ధరను అంచనా వేయండి',
    'predict.form.predicting': 'అంచనా వేస్తున్నాము...',
    'predict.form.areaExcludingBasement': 'నేలమాళిక తప్ప వైశాల్యం (చ.అడుగులు)',
    'predict.form.areaOfBasement': 'నేలమాళిక వైశాల్యం (చ.అడుగులు)',
    'predict.form.postalCode': 'పోస్టల్ కోడ్',
    'predict.form.latitude': 'అక్షాంశం',
    'predict.form.longitude': 'రేఖాంశం',
    'predict.form.views': 'వీక్షణల సంఖ్య',
    'predict.form.waterfront': 'వాటర్‌ఫ్రంట్ ఆస్తి',
    'predict.form.renovationYear': 'పునర్నిర్మాణ సంవత్సరం',
    'predict.form.schoolsNearby': 'సమీప పాఠశాలలు',
    'predict.form.distanceFromAirport': 'విమానాశ్రయం నుండి దూరం (కిమీ)',
    'predict.form.dimensions': 'ఆస్తి కొలతలు',
    'predict.form.rooms': 'గదుల ఆకృతీకరణ',
    'predict.form.quality': 'నాణ్యత & స్థితి',
    'predict.form.history': 'ఆస్తి చరిత్ర',
    'predict.form.locationDetails': 'స్థాన వివరాలు',
    'predict.form.features': 'ప్రత్యేక లక్షణాలు',
    'predict.form.neighborhood': 'పరిసరాలు & ప్రాప్యత',
    'predict.form.quickStart': 'త్వరిత ప్రారంభ ప్రీసెట్‌లు',
    'predict.form.budgetHome': 'బడ్జెట్ ఇల్లు',
    'predict.form.averageHome': 'సాధారణ ఇల్లు',
    'predict.form.luxuryEstate': 'లగ్జరీ ఎస్టేట్',
    'predict.form.aiValuation': 'AI ఆస్తి మూల్యాంకనం',
    'predict.form.poweredBy': '25-లక్షణాలు XGBoost ML మోడల్ ద్వారా శక్తివంతం',
    'predict.form.accuracy': 'ఖచ్చితత్వం',
    'predict.form.featuresCount': 'లక్షణాలు',
    'predict.form.properties': 'ఆస్తులు',
    'predict.form.submitPoweredBy': 'XGBoost ML తో 95.97% ఖచ్చితత్వంతో శక్తివంతం • సెకన్లలో ఫలితాలు',
    'predict.form.generateValuation': 'AI ఆస్తి మూల్యాంకనం జనరేట్ చేయండి',
    'predict.results.title': 'అంచనా వేసిన విలువ',
    'predict.results.confidence': 'విశ్వాసం',
    'predict.results.modelAccuracy': 'మోడల్ ఖచ్చితత్వం',
    'predict.results.analysis': 'మార్కెట్ విశ్లేషణ',
    'predict.results.estimatedValue': 'అంచనా వేసిన ఆస్తి విలువ',
    'predict.results.marketAnalysis': 'మార్కెట్ విశ్లేషణ',
    'predict.results.keyInsights': 'ముఖ్య అంతర్దృష్టులు',
    'predict.results.investmentCalculator': 'పెట్టుబడి కాలిక్యులేటర్',
    'predict.results.propertyLocation': 'ఆస్తి స్థానం',
    'predict.results.downPayment': 'డౌన్ పేమెంట్',
    'predict.results.monthlyMortgage': 'మాసిక తనఖా (అంచనా)',
    'predict.results.coordinates': 'కోఆర్డినేట్‌లు',
    'predict.results.priceRange': 'ధర పరిధి',
    'predict.results.locationRating': 'స్థాన రేటింగ్',
    'predict.results.propertyGrade': 'ఆస్తి గ్రేడ్',
    'predict.results.investmentAdvice': 'పెట్టుబడి సలహా',
    'predict.results.sizeFactor': 'పరిమాణ కారకం',
    'predict.results.locationPremium': 'స్థాన ప్రీమియం',
    'predict.results.predictionAccuracy': 'అంచనా ఖచ్చితత్వం',
    'predict.results.keyValueDrivers': 'ముఖ్య విలువ చోదకాలు',
    'predict.results.aiInsights': 'AI అంతర్దృష్టులు & ఆస్తుల పోలిక పొందండి',
    'predict.results.aiInsightsDesc': 'ఈ అంచనా గురించి మా AI అసిస్టెంట్‌కి ప్రశ్నలు అడగండి, ఇలాంటి ఆస్తులతో పోల్చండి, లేదా మీ నిర్దిష్ట అవసరాలపై ఆధారపడి పెట్టుబడి సలహా పొందండి.',
    'predict.results.chatAboutProperty': 'ఈ ఆస్తి గురించి చాట్ చేయండి',
    'predict.results.relatedProperties': 'సంబంధిత ఆస్తులు & మ్యాప్ స్థానం',
    'predict.results.similarProperties': 'దొరికిన సమాన ఆస్తులు',
    'predict.results.mapLocation': 'మ్యాప్ స్థానం',
    'predict.results.viewDetails': 'వివరాలు చూడండి',
    
    // Analytics Page
    'analytics.title': 'మార్కెట్ విశ్లేషణలు',
    'analytics.subtitle': 'సమగ్ర రియల్ ఎస్టేట్ మార్కెట్ అంతర్దృష్టులు మరియు ట్రెండ్‌లు',
    'analytics.overview': 'మార్కెట్ అవలోకనం',
    'analytics.trends': 'ధర ట్రెండ్‌లు',
    'analytics.distribution': 'ధర పంపిణీ',
    'analytics.investment': 'పెట్టుబడి కాలిక్యులేటర్',
    'analytics.roi': 'ROI విశ్లేషణ',
    'analytics.rental': 'అద్దె',
    'analytics.emi': 'EMI',
    'analytics.compare': 'పోల్చండి',
    'analytics.investmentDashboard': 'పెట్టుబడి విశ్లేషణ డాష్‌బోర్డ్',
    'analytics.dashboardSubtitle': 'ROI, అద్దె మరియు EMI అంతర్దృష్టులతో డేటా-ఆధారిత రియల్ ఎస్టేట్ నిర్ణయాలు తీసుకోండి.',
    'analytics.currentlyAnalyzing': 'ప్రస్తుతం విశ్లేషిస్తోంది',
    'analytics.clearSelection': 'ఎంపికను క్లియర్ చేయండి',
    'analytics.roiProjection': '10వ ROI',
    'analytics.rentalYield': 'అద్దె దిగుబడి',
    'analytics.monthlyEmi': 'మాసిక EMI',
    'analytics.totalInterest': 'మొత్తం వడ్డీ',
    'analytics.projectionBased': 'అభిమతిపై ఆధారపడిన అంచనా',
    'analytics.annualRentVs': 'వార్షిక అద్దె vs. ఆస్తి విలువ',
    'analytics.basedOnRate': 'రేటు మరియు కాలంపై ఆధారపడింది',
    'analytics.overFullTenure': 'పూర్తి రుణ కాలంలో',
    'analytics.roiCalculator': 'ROI కాలిక్యులేటర్',
    'analytics.rentalAnalyzer': 'అద్దె ఆదాయ విశ్లేషకి',
    'analytics.emiCalculator': 'EMI కాలిక్యులేటర్',
    'analytics.comparison': 'పోల్చండి',
    'analytics.purchasePrice': 'కొనుగోలు ధర (CAD)',
    'analytics.loanAmount': 'రుణ మొత్తం (CAD)',
    'analytics.interestRate': 'వడ్డీ రేటు (%)',
    'analytics.loanTenure': 'రుణ కాలం (సంవత్సరాలు)',
    'analytics.monthlyRent': 'ఆశించిన మాసిక అద్దె (CAD)',
    'analytics.appreciation': 'వార్షిక అభిమతి (%)',
    'analytics.investmentSummary': 'పెట్టుబడి సారాంశం',
    'analytics.projectedValue': 'అంచనా విలువ (10వ)',
    'analytics.totalGains': 'మొత్తం మూలధన లాభాలు',
    'analytics.returnOnInvestment': 'పెట్టుబడిపై రిటర్న్',
    'analytics.cashFlow': 'మాసిక నగదు ప్రవాహం',
    'analytics.breakEven': 'బ్రేక్-ఈవెన్ కాలం',
    'analytics.rentalSummary': 'అద్దె ఆదాయ విశ్లేషణ',
    'analytics.grossYield': 'స్థూల అద్దె దిగుబడి',
    'analytics.monthlyIncome': 'మాసిక అద్దె ఆదాయం',
    'analytics.annualIncome': 'వార్షిక అద్దె ఆదాయం',
    'analytics.tenYearIncome': '10-సంవత్సరాల అద్దె ఆదాయం',
    'analytics.emiBreakdown': 'EMI విభజన',
    'analytics.principalVsInterest': 'మూలధనం vs వడ్డీ',
    'analytics.paymentSchedule': 'కాలక్రమంలో చెల్లింపు షెడ్యూల్',
    
    // Additional Telugu Analytics Keys
    'analytics.propertyNumber': 'ఆస్తి',
    'analytics.sqft': 'చ.అడుగులు',
    'analytics.grade': 'గ్రేడ్',
    'analytics.configureInvestmentParameters': 'పెట్టుబడి పారామీటర్లను కాన్ఫిగర్ చేయండి',
    'analytics.investmentCalculator': 'పెట్టుబడి కాలిక్యులేటర్',
    'analytics.basedOnRateAndTenure': 'రేటు మరియు కాలంపై ఆధారపడింది',
    'analytics.overFullLoanTenure': 'పూర్తి రుణ కాలంలో',
    
    // Predict Related Properties
    'predict.related.title': 'సంబంధిత ఆస్తులు',
    'predict.related.mapLocation': 'మ్యాప్ స్థానం',
    'predict.related.similarProperties': 'దొరికిన సమాన ఆస్తులు',
    'predict.related.match': 'సరిపోలిక',
    'predict.related.beds': 'బెడ్‌లు',
    'predict.related.baths': 'బాత్‌లు',
    'predict.related.sqft': 'చ.అడుగులు',
    'predict.related.grade': 'గ్రేడ్',
    'predict.related.waterfront': 'వాటర్‌ఫ్రంట్',
    'predict.related.viewOnMap': 'మ్యాప్‌లో చూడండి',
    'predict.related.viewDetails': 'వివరాలు చూడండి',
    'predict.related.propertyDetails': 'ఆస్తి వివరాలు',
    'predict.related.gradeLuxury': 'లగ్జరీ',
    'predict.related.gradeExcellent': 'అత్యుత్తమం',
    'predict.related.gradeVeryGood': 'చాలా మంచిది',
    'predict.related.gradeGood': 'మంచిది',
    'predict.related.gradeAverage': 'సాధారణం',
    'predict.related.gradeBelowAverage': 'సాధారణం కంటే తక్కువ',
    'predict.related.conditionExcellent': 'అత్యుత్తమం',
    'predict.related.conditionVeryGood': 'చాలా మంచిది',
    'predict.related.conditionGood': 'మంచిది',
    'predict.related.conditionFair': 'బాగుంది',
    'predict.related.conditionPoor': 'దయనీయం',
    'predict.related.bedrooms': 'పడకగదులు',
    'predict.related.bathrooms': 'స్నానపు గదులు',
    'predict.related.livingArea': 'నివాస వైశాల్యం (చ.అడుగులు)',
    'predict.related.lotSize': 'లాట్ పరిమాణం (చ.అడుగులు)',
    'predict.related.buildingInfo': 'భవన సమాచారం',
    'predict.related.builtYear': 'నిర్మాణ సంవత్సరం',
    'predict.related.yearsOld': 'సంవత్సరాలు పాతది',
    'predict.related.renovated': 'పునర్నిర్మాణం',
    'predict.related.numberOfFloors': 'అంతస్తుల సంఖ్య',
    'predict.related.condition': 'స్థితి',
    'predict.related.areaBreakdown': 'వైశాల్య విభజన',
    'predict.related.excludingBasement': 'నేలమాళిక తప్ప',
    'predict.related.basementArea': 'నేలమాళిక వైశాల్యం',
    'predict.related.totalLivingArea': 'మొత్తం నివాస వైశాల్యం',
    'predict.related.postRenovation': 'పునర్నిర్మాణం తరువాత',
    'predict.related.locationAmenities': 'స్థానం & సౌకర్యాలు',
    'predict.related.nearbySchools': 'సమీప పాఠశాలలు',
    'predict.related.airportDistance': 'విమానాశ్రయం దూరం',
    'predict.related.postalCode': 'పోస్టల్ కోడ్',
    'predict.related.yes': 'అవును',
    'predict.related.no': 'లేదు',
    'predict.related.viewsFeatures': 'వీక్షణలు & లక్షణాలు',
    'predict.related.numberOfViews': 'వీక్షణల సంఖ్య',
    'predict.related.propertyId': 'ఆస్తి ID',
    'predict.related.qualityIndicators': 'నాణ్యత సూచికలు',
    'predict.related.greatViews': 'అద్భుతమైన వీక్షణలు',
    'predict.related.newBuild': 'కొత్త నిర్మాణం',
    'predict.related.propertyInsights': 'ఆస్తి అంతర్దృష్టులు',
    'predict.related.lotCoverage': 'లాట్ కవరేజ్',
    'predict.related.sqFtPerBedroom': 'పడకగదకు చ.అడుగులు',
    'predict.related.cadPerSqFt': 'చ.అడుగుకు CAD',
    
    // Heatmap Page
    'heatmap.title': 'ఆస్తి ధర హీట్‌మ్యాప్',
    'heatmap.subtitle': 'వివిధ స్థానాలలో ఆస్తి ధరలను దృశ్యమానం చేయండి',
    'heatmap.legend': 'ధర పరిధి',
    'heatmap.low': 'తక్కువ',
    'heatmap.medium': 'మధ్యమం',
    'heatmap.high': 'ఎక్కువ',
    'heatmap.premium': 'ప్రీమియం',
    
    // Chatbot
    'chatbot.title': 'AI ఆస్తి సహాయకుడు',
    'chatbot.subtitle': 'తక్షణ ఆస్తి మూల్యాంకనలు, స్మార్ట్ సిఫార్సులు మరియు నిపుణుల పెట్టుబడి సలహాలను పొందండి',
    'chatbot.placeholder': 'మీరు ఏమి వెతుకుతున్నారో చెప్పండి... (ఉదా. \'600k కింద 3 బెడ్‌రూమ్\' లేదా \'మంచి వీక్షణలతో వాటర్‌ఫ్రంట్\')',
    'chatbot.voiceHint': 'వాయిస్ ఇన్‌పుట్ ఉపయోగించడానికి మైక్‌పై క్లిక్ చేయండి',
    'chatbot.quickActions': 'ప్రారంభించడానికి ప్రసిద్ధ శోధనలు:',
    'chatbot.listening': 'వింటున్నాం...',
    'chatbot.voiceComplete': 'వాయిస్ ఇన్‌పుట్ పూర్తయింది',
    'chatbot.speakNow': 'ఇప్పుడు మాట్లాడండి...',
    'chatbot.thinking': 'AI ఆలోచిస్తోంది',
    'chatbot.propertyResults': 'ఆస్తి ఫలితాలు',
    'chatbot.noProperties': 'ఇంకా ఆస్తులు లేవు',
    'chatbot.tryAsking': 'అడగడానికి ప్రయత్నించండి:',
    'chatbot.selectedProperty': 'ఎంచుకున్న ఆస్తి వివరాలు',
    'chatbot.askAI': 'ఈ ఆస్తి గురించి AIని అడగండి',
    
    // Dashboard
    'dashboard.title': 'డాష్‌బోర్డ్',
    'dashboard.welcome': 'తిరిగి స్వాగతం',
    'dashboard.recentPredictions': 'ఇటీవలి అంచనలు',
    'dashboard.favorites': 'మీ ఇష్టమైనవి',
    'dashboard.marketTrends': 'మార్కెట్ ట్రెండ్‌లు',
    'dashboard.quickActions': 'త్వరిత చర్యలు',
    
    // Common
    'common.search': 'వెతకండి',
    'common.filter': 'ఫిల్టర్',
    'common.sort': 'క్రమబద్ధీకరించండి',
    'common.save': 'సేవ్ చేయండి',
    'common.cancel': 'రద్దు చేయండి',
    'common.loading': 'లోడ్ అవుతోంది...',
    'common.error': 'దోషం',
    'common.success': 'విజయం',
    'common.bedrooms': 'పడకగదులు',
    'common.bathrooms': 'స్నానపు గదులు',
    'common.sqft': 'చ.అడుగులు',
    'common.price': 'ధర',
    'common.location': 'స్థానం',
    'common.waterfront': 'వాటర్‌ఫ్రంట్',
    'common.grade': 'గ్రేడ్',
    'common.condition': 'స్థితి',
    'common.builtYear': 'నిర్మాణ సంవత్సరం',
    'common.confidence': 'విశ్వాసం',
    'common.features': 'లక్షణాలు',
    'common.detected': 'గుర్తించబడింది',
    'common.beds': 'బెడ్‌లు',
    'common.baths': 'బాత్‌లు',
    
    // Footer
    'footer.description': 'ఖచ్చితమైన ఆస్తి మూల్యాంకనల కోసం AI-శక్తివంతమైన రియల్ ఎస్టేట్ ప్లాట్‌ఫారం',
    'footer.quickLinks': 'త్వరిత లింక్‌లు',
    'footer.features': 'లక్షణాలు',
    'footer.support': 'మద్దతు',
    'footer.legal': 'చట్టపరమైన',
    'footer.privacy': 'గోప్యతా విధానం',
    'footer.terms': 'సేవా నియమాలు',
    'footer.contact': 'మమ్మల్ని సంప్రదించండి',
    'footer.help': 'సహాయ కేంద్రం',
    'footer.rights': 'అన్ని హక్కులు రక్షించబడినవి',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    // Get saved language from localStorage or default to English
    const saved = localStorage.getItem('language') as Language;
    return saved && Object.keys(translations).includes(saved) ? saved : 'en';
  });

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  useEffect(() => {
    // Save language preference to localStorage
    localStorage.setItem('language', language);
    // Set document language attribute
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}